/* ═══════════════════════════════════════════════════════════════════
   KARTI — SET 3 · "IL-VILLAĠĠ KOLLU JAF"  (The Whole Village Knows)
   84 new cards · load AFTER cards.js AND set2.js
   Same schema: {id, n, e, f, r, t, lvl, atk, def, txt, eff, fx}
     txt = the joke only (pure flavour)
     eff = plain English of what the card actually does
   Brings the pool to exactly 200.
   ═══════════════════════════════════════════════════════════════════ */

/* ── NEW fx introduced by Set 3 (4 total) ──────────────────────────
   pierce     : excess battle damage dealt to a DEFENDING monster carries over to its owner's LP.
   drain      : on summon, the enemy monster with the highest ATK loses 400 ATK and this gains 400 ATK.
   s_discard  : SPELL — the opponent discards 1 card at random.
   t_mirror   : TRAP — negate the attack and deal the attacker's ATK to its controller as damage.
   ─────────────────────────────────────────────────────────────────── */
const SET3_FX = {
  pierce:    'Excess battle damage dealt to a defending monster carries over to the opponent\'s LP.',
  drain:     'On summon: the enemy monster with the highest ATK loses 400 ATK and this monster gains 400 ATK.',
  s_discard: 'SPELL: the opponent discards 1 card at random.',
  t_mirror:  'TRAP: negate the attack and deal the attacker\'s ATK to its controller as damage.',
};

const SET3 = [
  /* ══════════ FESTA 🎆 — the village, the noise, the committee ══════════ */
  {id:'sparkler',  n:'Kid With A Sparkler',      e:'🌟', f:'festa', r:'komuni', t:'monster', lvl:1, atk:900,  def:200,
   txt:'Six years old, holding open fire, and his father is four beers into a very relaxed evening.',
   eff:'No effect — level-1 glass-cannon attacker.', fx:''},
  {id:'bandalora', n:'The Festa Banner',         e:'🚩', f:'festa', r:'komuni', t:'monster', lvl:1, atk:300,  def:1100,
   txt:'Strung across the street in March. Still up in December. Nobody in the street owns a ladder.',
   eff:'No effect — cheap level-1 wall.', fx:''},
  {id:'kummissjoni',n:'The Festa Committee',     e:'📝', f:'festa', r:'komuni', t:'monster', lvl:2, atk:1000, def:900,
   txt:'Eleven men, one budget, four factions, and a group chat that has never once reached agreement.',
   eff:'No effect — balanced level-2 body.', fx:''},
  {id:'qniepen',   n:'Bells At Six In The Morning',e:'🔔', f:'festa', r:'komuni', t:'monster', lvl:2, atk:1100, def:500,
   txt:'Sunday. Six sharp. Rung by a man who has never had a lie-in and does not believe in them.',
   eff:'No effect — cheap level-2 attacker.', fx:''},
  {id:'armar',     n:'Street Decorations',       e:'🏮', f:'festa', r:'komuni', t:'monster', lvl:3, atk:1300, def:1300,
   txt:'Hand-carved, gold-leafed, and stored eleven months a year in a garage that floods every February.',
   eff:'No effect — balanced level-3 body.', fx:''},
  {id:'girandola', n:'The Catherine Wheel',      e:'🎡', f:'festa', r:'komuni', t:'monster', lvl:4, atk:1800, def:1300,
   txt:'Spins beautifully for eleven seconds, then leaves the frame and picks someone in the crowd personally.',
   eff:'No effect — solid level-4 beater.', fx:''},
  {id:'tromba',    n:'The Trumpet Solo',         e:'🎷', f:'festa', r:'komuni', t:'monster', lvl:4, atk:1500, def:1500,
   txt:'One man, one high note, zero chance. The whole square holds its breath and he misses it anyway.',
   eff:'No effect — balanced level-4 body.', fx:''},
  {id:'narmarina', n:'The Fireworks Barge',      e:'🚢', f:'festa', r:'rari',   t:'monster', lvl:5, atk:2200, def:1700,
   txt:'Fired from out at sea so the mistakes land in the water instead of on your aunt. Mostly.',
   eff:'Excess battle damage to a defending monster hits the opponent\'s LP.', fx:'pierce'},
  {id:'president', n:'The Committee President',  e:'🥇', f:'festa', r:'rari',   t:'monster', lvl:5, atk:2000, def:2500,
   txt:'Twenty-six years in that chair. There have been elections. He has won every single one of them.',
   eff:'Enemies must attack this monster first (Taunt).', fx:'taunt'},
  {id:'salut',     n:'The Twenty-One Bangs',     e:'💣', f:'festa', r:'rari',   t:'monster', lvl:6, atk:2400, def:1500,
   txt:'One at a time, each one landing exactly when you had finally relaxed from the last one.',
   eff:'When destroyed: 500 damage to BOTH players.', fx:'boom'},
  {id:'surmast',   n:'THE BANDMASTER',           e:'🎻', f:'festa', r:'leggendarju', t:'monster', lvl:7, atk:2900, def:2600,
   txt:'Sixty years on the podium. He has buried three committees and outlived every trumpet he ever shouted at.',
   eff:'On summon: steal 400 ATK from the strongest enemy monster.', fx:'drain'},
  {id:'bombi',     n:'The Midnight Barrage',     e:'🌋', f:'festa', r:'epiku',  t:'monster', lvl:8, atk:2800, def:2200,
   txt:'Fifteen unbroken minutes of explosions. Three car alarms, two dogs, and one tourist ringing his embassy.',
   eff:'When destroyed: 500 damage to BOTH players.', fx:'boom'},

  /* ══════════ FARM 🐇 — dirt, diesel, and a man who has decided ══════════ */
  {id:'naghga',    n:'One Lost Sheep',           e:'🐑', f:'razzett', r:'komuni', t:'monster', lvl:1, atk:500,  def:900,
   txt:'On the road, at night, on a blind corner — and somehow the insurance says it is your fault.',
   eff:'No effect — cheap level-1 body.', fx:''},
  {id:'patata',    n:'Gozo Potatoes',            e:'🥔', f:'razzett', r:'komuni', t:'monster', lvl:1, atk:400,  def:1300,
   txt:'Sold from the back of a van by a man who will not say which field, which island, or which year.',
   eff:'When summoned: heal 500 LP.', fx:'heal'},
  {id:'karettun',  n:'The Overloaded Pickup',    e:'🛻', f:'razzett', r:'komuni', t:'monster', lvl:2, atk:1100, def:800,
   txt:'Four crates of tomatoes, two dogs, one nephew standing up in the back, and not a single strap.',
   eff:'No effect — cheap level-2 attacker.', fx:''},
  {id:'dielja',    n:'The Vine In The Yard',     e:'🍇', f:'razzett', r:'komuni', t:'monster', lvl:2, atk:500,  def:1600,
   txt:'Makes a wine that could strip an engine block. Every year he gives you a bottle. Every year you take it.',
   eff:'No effect — cheap level-2 wall.', fx:''},
  {id:'frawli',    n:'Strawberry Season',        e:'🍓', f:'razzett', r:'komuni', t:'monster', lvl:3, atk:1400, def:1300,
   txt:'Two weeks, one festival, and a queue of cars that reaches back into the next village.',
   eff:'No effect — balanced level-3 body.', fx:''},
  {id:'bir',       n:'The Old Well',             e:'🪣', f:'razzett', r:'komuni', t:'monster', lvl:3, atk:700,  def:1600,
   txt:'Dry since 1974. Still on the deeds. Still adds eleven thousand to the asking price.',
   eff:'No effect — cheap level-3 wall.', fx:''},
  {id:'hmar',      n:'The Stubborn Donkey',      e:'🫏', f:'razzett', r:'komuni', t:'monster', lvl:4, atk:1700, def:1300,
   txt:'He has decided. You have not been told what he decided, and you will not be. But he has decided.',
   eff:'No effect — solid level-4 body.', fx:''},
  {id:'bettieha',  n:'The Watermelon Van',       e:'🍉', f:'razzett', r:'komuni', t:'monster', lvl:4, atk:1600, def:1400,
   txt:'Through the village at six with a loudspeaker shouting the price. The price is never the price.',
   eff:'No effect — balanced level-4 body.', fx:''},
  {id:'klieb',     n:'The Hunting Dogs',         e:'🐩', f:'razzett', r:'rari',   t:'monster', lvl:4, atk:1800, def:1100,
   txt:'Two of them, ninety kilos between them, and neither has been fed since the argument started.',
   eff:'Attacks two enemy monsters in one battle phase.', fx:'cleave'},
  {id:'serra',     n:'The Plastic Greenhouse',   e:'🌱', f:'razzett', r:'rari',   t:'monster', lvl:5, atk:2200, def:1900,
   txt:'Held down with old tyres, blue string and pure stubbornness. The wind has tried nine times.',
   eff:'First time it would be destroyed in battle, it survives instead.', fx:'shield'},
  {id:'mahzen',    n:'The Farm Shed',            e:'🛖', f:'razzett', r:'rari',   t:'monster', lvl:6, atk:2200, def:2300,
   txt:'Tools, diesel, a fridge of beer, and a rifle that officially has never existed and never will.',
   eff:'On summon: every enemy monster loses 400 ATK.', fx:'weaken'},

  /* ══════════ CITY 🏰 — forms, dust, and nowhere to park ══════════ */
  {id:'garaxx',    n:'The Garage With No Car In It',e:'🧰', f:'belt', r:'komuni', t:'monster', lvl:1, atk:300,  def:1200,
   txt:'A sofa, a fridge, a television and six men. The actual car has lived on the street since 2003.',
   eff:'No effect — cheap level-1 wall.', fx:''},
  {id:'kju',       n:'Ticket Number 84',         e:'🎫', f:'belt', r:'komuni', t:'monster', lvl:1, atk:600,  def:700,
   txt:'They are serving 31. There are two windows. One is closed and the other is on a personal call.',
   eff:'No effect — cheap level-1 body.', fx:''},
  {id:'vespa',     n:'The Delivery Scooter',     e:'🛵', f:'belt', r:'komuni', t:'monster', lvl:2, atk:1200, def:400,
   txt:'Pavement, red light, one-way street, phone in one hand. Your food is hot and the man is a legend.',
   eff:'No effect — cheap level-2 attacker.', fx:''},
  {id:'hanut',     n:'The Corner Shop',          e:'🏪', f:'belt', r:'komuni', t:'monster', lvl:2, atk:700,  def:1400,
   txt:'No price on anything. Somehow the total always comes to exactly what you have in your pocket.',
   eff:'No effect — cheap level-2 wall.', fx:''},
  {id:'rota',      n:'The Roundabout',           e:'🔄', f:'belt', r:'komuni', t:'monster', lvl:3, atk:900,  def:1700,
   txt:'Four lanes go in. Nobody has ever formally established how many are meant to come out.',
   eff:'No effect — cheap level-3 wall.', fx:''},
  {id:'kaxxier',   n:'The Supermarket Cashier',  e:'🛒', f:'belt', r:'komuni', t:'monster', lvl:3, atk:1300, def:1300,
   txt:'Nine hundred items an hour and has not blinked since 2019. Do not, under any circumstances, ask for a bag.',
   eff:'No effect — balanced level-3 body.', fx:''},
  {id:'sinjal',    n:'The Sign Facing The Wall', e:'🚸', f:'belt', r:'komuni', t:'monster', lvl:4, atk:1300, def:1800,
   txt:'Points at a street demolished in 2016. Nobody in the entire country has the authority to turn it.',
   eff:'No effect — level-4 wall.', fx:''},
  {id:'spettur',   n:'The Speed Camera',         e:'📸', f:'belt', r:'rari',   t:'monster', lvl:4, atk:1600, def:1500,
   txt:'Flashed you at four in the morning on an empty road. The letter arrives the day you get paid.',
   eff:'When summoned: opponent loses 800 LP.', fx:'burn'},
  {id:'bank',      n:'The Bank Appointment',     e:'🏦', f:'belt', r:'rari',   t:'monster', lvl:5, atk:2000, def:2400,
   txt:'Six weeks for a slot, forty minutes of questions, and in the end you did not have the right letter.',
   eff:'When summoned: enemy monsters cannot attack next turn.', fx:'stun'},
  {id:'taxxa',     n:'The Tax Return',           e:'📊', f:'belt', r:'rari',   t:'monster', lvl:5, atk:2300, def:1700,
   txt:'Due in June. Started in June. The wrong June.',
   eff:'Battle damage it deals to the opponent also heals you that amount.', fx:'leech'},
  {id:'klinika',   n:'The Private Clinic',       e:'🩺', f:'belt', r:'rari',   t:'monster', lvl:6, atk:2300, def:2100,
   txt:'Seen in nine minutes, out in twelve, and the bill grows a little every time you look away from it.',
   eff:'Gains +200 ATK each of your turns.', fx:'grow'},
  {id:'tribunal',  n:'The Law Courts',           e:'⚖️', f:'belt', r:'epiku',  t:'monster', lvl:7, atk:2700, def:2900,
   txt:'Adjourned. Adjourned again. Your grandchildren will hear the verdict and they will not care.',
   eff:'When summoned: enemy monsters cannot attack next turn.', fx:'stun'},

  /* ══════════ SEA 🌊 — salt, sunburn, and a shoulder that never recovers ══════════ */
  {id:'qroll',     n:'Coral In The Pocket',      e:'🪸', f:'bahar', r:'komuni', t:'monster', lvl:1, atk:400,  def:1000,
   txt:'Taken from the sea by a man who will then lecture you for an hour about protecting the sea.',
   eff:'No effect — cheap level-1 wall.', fx:''},
  {id:'xemx',      n:'Aftersun At Midnight',     e:'🧴', f:'bahar', r:'komuni', t:'monster', lvl:2, atk:600,  def:1500,
   txt:'Cold cream, hot skin, and a shape on your back that is unmistakably a vest.',
   eff:'No effect — cheap level-2 wall.', fx:''},
  {id:'xlokk',     n:'The Sirocco',              e:'🍃', f:'bahar', r:'komuni', t:'monster', lvl:2, atk:800,  def:1300,
   txt:'Warm, wet, straight up from Africa, and it makes every door in the house slam at three in the morning.',
   eff:'No effect — cheap level-2 wall.', fx:''},
  {id:'mask',      n:'Leaky Snorkel Mask',       e:'🤿', f:'bahar', r:'komuni', t:'monster', lvl:3, atk:1200, def:1400,
   txt:'Twelve euro from the beach shop. Leaks in exactly one place and you will never locate it.',
   eff:'No effect — level-3 body with decent defence.', fx:''},
  {id:'nassa',     n:'The Fish Trap',            e:'🪝', f:'bahar', r:'komuni', t:'monster', lvl:3, atk:1600, def:700,
   txt:'Left out three days. Two fish, one shoe, and something nobody on the boat wants to identify.',
   eff:'No effect — efficient level-3 attacker.', fx:''},
  {id:'xugaman',   n:'The 7am Towel Claim',      e:'🧺', f:'bahar', r:'komuni', t:'monster', lvl:4, atk:700,  def:2100,
   txt:'Eight sunbeds claimed at dawn by one man who will not physically appear until eleven.',
   eff:'No effect — level-4 wall.', fx:''},
  {id:'jetski',    n:'The Rented Jet Ski',       e:'🏄', f:'bahar', r:'komuni', t:'monster', lvl:4, atk:1900, def:600,
   txt:'Sixty euro for fifteen minutes of terrorising the whole bay and one very personal moment with a kayak.',
   eff:'No effect — high ATK, very low DEF.', fx:''},
  {id:'pixxispad', n:'The Swordfish',            e:'🗡️', f:'bahar', r:'epiku',  t:'monster', lvl:5, atk:2300, def:1600,
   txt:'Three metres of muscle with a nose like a lance. It has been hooked twice and it remembers both times.',
   eff:'Excess battle damage to a defending monster hits the opponent\'s LP.', fx:'pierce'},
  {id:'regatta',   n:'The Regatta Crew',         e:'🚣', f:'bahar', r:'rari',   t:'monster', lvl:5, atk:2100, def:2000,
   txt:'Eight men who have not spoken since last September, rowing in perfect time for exactly four minutes.',
   eff:'Can attack twice each battle phase.', fx:'double'},
  {id:'maltemp',   n:'The Winter Storm',         e:'⛈️', f:'bahar', r:'rari',   t:'monster', lvl:6, atk:2400, def:1900,
   txt:'Half the promenade ends up in the road and one boat ends up on a roundabout. Everyone films it. Nobody moves it.',
   eff:'On summon: steal 400 ATK from the strongest enemy monster.', fx:'drain'},

  /* ══════════ TROUBLE 😈 — family, money, and other people ══════════ */
  {id:'email',     n:'The 11pm Work Email',      e:'📧', f:'hazen', r:'komuni', t:'monster', lvl:1, atk:600,  def:800,
   txt:'"No rush." Sent at eleven. He can see the two blue ticks and you both know exactly what this is.',
   eff:'No effect — cheap level-1 body.', fx:''},
  {id:'qarrejja',  n:'The Coffee Cup Reader',    e:'🍵', f:'hazen', r:'komuni', t:'monster', lvl:2, atk:1100, def:700,
   txt:'Sees a wedding, a journey and a betrayal in your leftovers. Two of the three will happen this month.',
   eff:'No effect — cheap level-2 attacker.', fx:''},
  {id:'festin',    n:'The Christening Party',    e:'🍼', f:'hazen', r:'komuni', t:'monster', lvl:3, atk:1400, def:1000,
   txt:'Two hundred guests for a baby who will not remember any of it. Neither will half the guests.',
   eff:'No effect — level-3 body.', fx:''},
  {id:'partit',    n:'The Football Argument',    e:'⚽', f:'hazen', r:'komuni', t:'monster', lvl:3, atk:1600, def:700,
   txt:'Two men roaring about a team from another country, in a village neither of them has ever left.',
   eff:'No effect — efficient level-3 attacker.', fx:''},
  {id:'karaoke',   n:'Karaoke At Half One',      e:'🎤', f:'hazen', r:'komuni', t:'monster', lvl:4, atk:1800, def:900,
   txt:'He has the microphone, he has the wrong key, and he has four more queued under a false name.',
   eff:'No effect — level-4 attacker with soft defence.', fx:''},
  {id:'bocci',     n:'The Bocci Dispute',        e:'🥎', f:'hazen', r:'rari',   t:'monster', lvl:4, atk:1500, def:1800,
   txt:'Out came the tape measure. Then the spirit level. Then the 1997 rulebook and the man who claims he wrote it.',
   eff:'When summoned: look at the opponent\'s hand.', fx:'peek'},
  {id:'wirt',      n:'The Inheritance',          e:'🏺', f:'hazen', r:'rari',   t:'monster', lvl:5, atk:2200, def:1800,
   txt:'Nine siblings, one farmhouse, and a will written in 1962 on the back of a feed bag.',
   eff:'Opponent discards 1 card each of your turns.', fx:'discard'},
  {id:'ommgharusa',n:'The Bride\'s Mother',      e:'👰', f:'hazen', r:'rari',   t:'monster', lvl:6, atk:2300, def:2000,
   txt:'The dress, the flowers, the seating plan and the budget are all hers now. It was never your wedding.',
   eff:'Gains +300 ATK each of your turns.', fx:'grow2'},
  {id:'kondominju',n:'The Block Meeting',        e:'🗳️', f:'hazen', r:'epiku', t:'monster', lvl:6, atk:2400, def:2400,
   txt:'Eleven owners, one broken lift, four hours, and a unanimous decision to meet again in three months.',
   eff:'When summoned: enemy monsters cannot attack next turn.', fx:'stun'},
  {id:'kredituri', n:'THE DEBT COLLECTORS',      e:'🕴️', f:'hazen', r:'epiku', t:'monster', lvl:8, atk:2800, def:2600,
   txt:'Two men in a small car who know your registration, your shift pattern and your mother\'s address.',
   eff:'Excess battle damage to a defending monster hits the opponent\'s LP.', fx:'pierce'},

  /* ══════════ SPELLS ══════════ */
  {id:'qassata',   n:'Qassata Tal-Irkotta',      e:'🥧', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Twice the size of a pastizz and four times the guilt. You will still buy two of them.',
   eff:'Draw 1 card.', fx:'s_draw1'},
  {id:'imqaret',   n:'Imqaret By The Gate',      e:'🍯', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Fried date pastry from a van at midnight. Removes the roof of your mouth. Worth it every time.',
   eff:'Draw 1 card.', fx:'s_draw1'},
  {id:'mistura',   n:'Nanna\'s Cure-All',        e:'🧪', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Honey, lemon, whisky and one ingredient she will not name. It works. Nobody knows why. Nobody asks.',
   eff:'Draw 1 card.', fx:'s_draw1'},
  {id:'granita',   n:'Granita On The Steps',     e:'🍧', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Melts faster than you can drink it, so now your hand is sticky until roughly September.',
   eff:'Draw 1 card.', fx:'s_draw1'},
  {id:'kwarezimal',n:'Kwareżimal In Lent',       e:'🍪', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'No butter, no eggs, no fun — a sweet invented specifically to remind you that you gave something up.',
   eff:'Draw 1 card.', fx:'s_draw1'},
  {id:'siggu',     n:'Bring Your Own Chair',     e:'💺', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'The whole street sits outside after dinner and nobody goes in until somebody gets cold.',
   eff:'Draw 2 cards.', fx:'s_draw'},
  {id:'weekend',   n:'Long Weekend In Gozo',     e:'🗺️', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Two nights, one farmhouse, eleven people and one bathroom. You will not come back rested.',
   eff:'Draw 2 cards.', fx:'s_draw'},
  {id:'tombla',    n:'Tombla On A Sunday',       e:'🎱', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Nanna has four cards, a pen in each hand and murder in her eyes. Do not speak during the numbers.',
   eff:'Draw 2 cards.', fx:'s_draw'},
  {id:'baharkalm', n:'Flat Calm At Dawn',        e:'🌅', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Six in the morning, not a ripple, not a soul. By ten it will be forty people and a speaker.',
   eff:'Draw 2 cards.', fx:'s_draw'},
  {id:'helwa',     n:'Ħelwa Tat-Tork',           e:'🍫', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'One spoonful and your dentist can finally put a deposit on the boat.',
   eff:'Target 1 monster: +700 ATK until end of turn.', fx:'s_buff'},
  {id:'tea',       n:'Tea With Six Sugars',      e:'🫖', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Made by a man who has never once asked anybody how they take it, and never will.',
   eff:'Target 1 monster: +700 ATK until end of turn.', fx:'s_buff'},
  {id:'xalata',    n:'The Village Outing',       e:'🚍', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'One coach, forty pensioners, a crate of beer, and a driver who stopped fighting it years ago.',
   eff:'Target 1 monster: +700 ATK until end of turn.', fx:'s_buff'},
  {id:'qaghaq',    n:'Qagħaq Tal-Għasel',        e:'🍩', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'A ring of pastry, a river of treacle, and a shirt that is now permanently retired.',
   eff:'Target 1 monster: +700 ATK until end of turn.', fx:'s_buff'},
  {id:'whisky',    n:'The Duty Free Whisky',     e:'🥃', f:null, r:'komuni', t:'spell', lvl:0, atk:0, def:0,
   txt:'Bought at the airport in July, opened at Christmas, finished before Boxing Day lunch.',
   eff:'Target 1 monster: +700 ATK until end of turn.', fx:'s_buff'},
  {id:'kappella',  n:'A Word With The Saint',    e:'🕊️', f:null, r:'rari', t:'spell', lvl:0, atk:0, def:0,
   txt:'Two euro in the box, one candle, and a request that is frankly enormous for two euro.',
   eff:'Heal 1500 LP.', fx:'s_heal'},
  {id:'wirja',     n:'The Village Exhibition',   e:'🖼️', f:null, r:'rari', t:'spell', lvl:0, atk:0, def:0,
   txt:'Model boats, old photographs, and a man who will explain every single one of them to you personally.',
   eff:'Add one monster from your deck to your hand.', fx:'s_search'},
  {id:'screenshot',n:'The Screenshot',           e:'📲', f:null, r:'rari', t:'spell', lvl:0, atk:0, def:0,
   txt:'You sent it to the group. You meant to send it to one person. It was about someone in the group.',
   eff:'Opponent discards 1 card at random.', fx:'s_discard'},
  {id:'inawgurazzjoni',n:'The Ribbon Cutting',   e:'✂️', f:null, r:'rari', t:'spell', lvl:0, atk:0, def:0,
   txt:'Three speeches, one pair of scissors, and a road that will be dug up again before April.',
   eff:'All your monsters gain +400 ATK this turn.', fx:'s_buffall'},
  {id:'bulldozer', n:'Sunday Morning Demolition',e:'🚧', f:null, r:'epiku', t:'spell', lvl:0, atk:0, def:0,
   txt:'The permit says "minor internal works". Half the terrace is currently in a skip on the pavement.',
   eff:'Destroy 1 enemy monster.', fx:'s_destroy'},
  {id:'cavetta',   n:'The Spare Key Under The Pot',e:'🔑', f:null, r:'epiku', t:'spell', lvl:0, atk:0, def:0,
   txt:'Everybody in the family knows where it is. Including the ones you no longer speak to.',
   eff:'Take control of 1 enemy monster until end of turn.', fx:'s_steal'},

  /* ══════════ TRAPS ══════════ */
  {id:'hofra',     n:'The Pothole',              e:'🛞', f:null, r:'komuni', t:'trap', lvl:0, atk:0, def:0,
   txt:'Reported in 2019. Filled in 2021. Reopened in 2021, slightly wider and much angrier.',
   eff:'Attacking monster loses 800 ATK this battle.', fx:'t_weaken'},
  {id:'qtar',      n:'The Air Conditioner Drip', e:'💧', f:null, r:'komuni', t:'trap', lvl:0, atk:0, def:0,
   txt:'Three floors up, straight down the back of your neck, and no way on earth to prove which flat.',
   eff:'Attacking monster loses 800 ATK this battle.', fx:'t_weaken'},
  {id:'zibel',     n:'The Bag Left Out Early',   e:'🗑️', f:null, r:'komuni', t:'trap', lvl:0, atk:0, def:0,
   txt:'Collection is Tuesday. It is Sunday. The cats have already given their review of the contents.',
   eff:'Attacking monster loses 800 ATK this battle.', fx:'t_weaken'},
  {id:'hass',      n:'Cramp, Straight After Lunch',e:'🦵', f:null, r:'komuni', t:'trap', lvl:0, atk:0, def:0,
   txt:'You had a ftira twenty minutes ago, you swam out anyway, and your mother warned you about this exact moment.',
   eff:'Attacking monster loses 800 ATK this battle.', fx:'t_weaken'},
  {id:'wegha',     n:'The Promise You Made',     e:'📿', f:null, r:'komuni', t:'trap', lvl:0, atk:0, def:0,
   txt:'Made at three in the morning in a very bad moment. It is now daylight and it is fully binding.',
   eff:'Negate 1 attack.', fx:'t_negate'},
  {id:'barriera',  n:'Road Closed For The Festa',e:'🚫', f:null, r:'komuni', t:'trap', lvl:0, atk:0, def:0,
   txt:'No warning, no diversion, and the man on the barrier does not care that you live behind it.',
   eff:'Negate 1 attack.', fx:'t_negate'},
  {id:'garanzija', n:'The Warranty Ran Out',     e:'📉', f:null, r:'rari', t:'trap', lvl:0, atk:0, def:0,
   txt:'Two years and eleven days. The machine knew. The machine waited.',
   eff:'Opponent loses 1000 LP.', fx:'t_burn'},
  {id:'tiswija',   n:'"He Never Came Back"',     e:'🔧', f:null, r:'rari', t:'trap', lvl:0, atk:0, def:0,
   txt:'Took the deposit, took the measurements, took the actual door. That was in March.',
   eff:'Return the attacking monster to its owner\'s hand.', fx:'t_bounce'},
  {id:'nannathares',n:'NANNA IS ON THE BALCONY', e:'👀', f:null, r:'leggendarju', t:'trap', lvl:0, atk:0, def:0,
   txt:'She has not left that balcony since 1988. She saw you. She saw all of it. It comes up at Christmas.',
   eff:'Negate the attack and deal the attacker\'s ATK to its controller as damage.', fx:'t_mirror'},
];

/* ══════════ merge into the live pool ══════════ */
CARDS.push(...SET3);

/* ═══════════ TWO NEW 40-CARD DECKS ═══════════
   Both sit on existing attributes so the five-way counter ring is untouched:
   IL-KAŻIN  = FESTA   → beats CITY,  loses to TROUBLE
   IL-FAMILJA = TROUBLE → beats FESTA, loses to SEA
   (`f` names the attribute this deck plays, for any attribute-aware code.) */
const SET3_DECKS = {
  kazin: {
    name:'IL-KAŻIN', e:'🍻', c:'#E8452C', f:'festa',
    tag:'Grind — hold the square with taunts, tick them down, and never close the bar',
    beats:'CITY', loses:'TROUBLE',
    list:{ sparkler:3, qniepen:3, kummissjoni:2, armar:3, girandola:3, tromba:2,
           kazin:2, president:2, narmarina:1, salut:2, surmast:1,
           helwa:3, tombla:2, xalata:2, inawgurazzjoni:2, kappella:1,
           hofra:2, wegha:2, garanzija:1, nannathares:1 },
  },
  familja: {
    name:'IL-FAMILJA', e:'🍼', c:'#37474F', f:'hazen',
    tag:'Attrition — read their hand, empty it, and outlast the whole miserable afternoon',
    beats:'FESTA', loses:'SEA',
    list:{ email:3, qarrejja:2, festin:2, partit:3, karaoke:3, bocci:3,
           wirt:2, ommgharusa:2, kondominju:2, kredituri:1,
           mistura:3, siggu:2, screenshot:2, wirja:1, cavetta:1, kappella:1,
           qtar:2, zibel:2, garanzija:2, tiswija:1 },
  },
};
Object.assign(STARTER_DECKS, SET3_DECKS);
