/* ═══════════════════════════════════════════════════════════════════
   KARTI — spy-words.js   ·   L-ISPJUN — the words

   The whole value of a hidden-word game is the pool: the moment the
   table starts seeing repeats, the game is dead. So this file is BIG
   on purpose, and OBJECTS is the deepest theme on purpose — it is the
   one people actually pick.

   EVERY ENTRY IS ONE WORD IN TWO LANGUAGES: [maltese, english].
   One entry, two labels — never two parallel lists that can drift and
   deal a spy a word half the table cannot see. Where a Maltese thing
   has no honest English name (il-ġostra, il-kusksu) the Maltese is
   kept in both, exactly as a name that does not translate carries
   across in the other direction (Shrek is Shrek).

   THE TEST FOR AN ENTRY: can the table ask questions about it without
   handing the spy the answer? A word needs a place, a price, a noise,
   a smell or a ritual attached. "Vase" is thin; "the junk drawer" is
   a round. Concept words with nothing to ask about were dropped.

   Maltese notes for whoever edits this:
     · the article assimilates to ċ d n r s t x z ż (iċ-, id-, in-,
       ir-, is-, it-, ix-, iz-, iż-), l- before a vowel or għ/silent h,
       l-i… before a consonant cluster (l-iskola), il- otherwise.
       Loanwords assimilate BY SOUND: iċ-chewing gum, ix-Shein.
     · brand names appear only as puzzle answers — nominative use,
       no endorsement, and the app's own copy stays neutral about
       every one of them.
   ═══════════════════════════════════════════════════════════════════ */
'use strict';

(function(){

const T = [];
function th(id, mt, en, ico, words){ T.push({ id, mt, en, ico, words }); }

/* ── OBJECTS — the deep one ─────────────────────────────────────────
   Spread across kitchens, cars, toolboxes, handbags, bathrooms,
   beaches, offices, churches, toy boxes, nanna's front room, tech and
   wardrobes, so the questions never all sound the same. */
th('objects', 'Oġġetti', 'Objects', 'sp-box', [
  /* kitchen */
  ['il-kitla', 'the kettle'],
  ['il-mgħarfa', 'the spoon'],
  ['il-furketta', 'the fork'],
  ['is-sikkina tal-ħobż', 'the bread knife'],
  ['il-platt', 'the plate'],
  ['il-kikkra', 'the mug'],
  ['it-tazza', 'the drinking glass'],
  ['il-friġġ', 'the fridge'],
  ['il-forn', 'the oven'],
  ['il-microwave', 'the microwave'],
  ['it-taġen', 'the frying pan'],
  ['il-borma', 'the cooking pot'],
  ['l-iskutella', 'the bowl'],
  ['it-tin opener', 'the tin opener'],
  ['il-corkscrew', 'the corkscrew'],
  ['l-għarbiel', 'the sieve'],
  ['il-biċċa tal-platti', 'the dishcloth'],
  ['it-toaster', 'the toaster'],
  ['il-blender', 'the blender'],
  ['l-air fryer', 'the air fryer'],
  ['il-grater tal-ġobon', 'the cheese grater'],
  ['it-tavla tat-tqattigħ', 'the chopping board'],
  ['is-srievet', 'the napkins'],
  ['il-ktieb tar-riċetti', 'the recipe book'],
  /* car */
  ['l-istering', 'the steering wheel'],
  ['il-handbrejk', 'the handbrake'],
  ['iċ-ċinturin tas-sigurtà', 'the seatbelt'],
  ['il-wajpers', 'the windscreen wipers'],
  ['il-boot tal-karozza', 'the car boot'],
  ['in-numru tal-karozza', 'the number plate'],
  ['il-ħorn', 'the car horn'],
  ['l-indikejter', 'the indicator'],
  ['il-ġakk', 'the car jack'],
  ['is-siġra tal-fwieħa', 'the little tree air freshener'],
  ['it-tajer tar-riżerva', 'the spare tyre'],
  ['il-liċenzja tal-karozza', 'the car licence disc'],
  /* toolbox */
  ['il-martell', 'the hammer'],
  ['it-tornavit', 'the screwdriver'],
  ['il-pinza', 'the pliers'],
  ['is-sellum', 'the ladder'],
  ['il-vit', 'the screw'],
  ['il-musmar', 'the nail'],
  ['il-metru', 'the measuring tape'],
  ['il-livell', 'the spirit level'],
  ['id-drill', 'the drill'],
  ['il-pinzell taż-żebgħa', 'the paintbrush'],
  ['iċ-ċavetta Allen', 'the Allen key'],
  ['l-extension lead', 'the extension lead'],
  ['il-kaxxa tal-għodda', 'the toolbox'],
  /* handbag */
  ['il-lipstik', 'the lipstick'],
  ['il-maktur', 'the handkerchief'],
  ['il-kartiera', 'the wallet'],
  ['iċ-ċwievet', 'the keys'],
  ['in-nuċċali tax-xemx', 'the sunglasses'],
  ['il-mera ż-żgħira', 'the pocket mirror'],
  ['iċ-chewing gum', 'the chewing gum'],
  ['il-fwieħa', 'the perfume'],
  ['iċ-ċarġer tal-mowbajl', 'the phone charger'],
  ['il-power bank', 'the power bank'],
  ['l-earphones', 'the earphones'],
  /* bathroom */
  ['id-doċċa', 'the shower'],
  ['il-banju', 'the bathtub'],
  ['it-tojlit', 'the toilet'],
  ['il-karta tat-tojlit', 'the toilet paper'],
  ['ix-xugaman', 'the towel'],
  ['is-sapuna', 'the bar of soap'],
  ['ix-xampù', 'the shampoo'],
  ['ix-xkupilja tas-snien', 'the toothbrush'],
  ['il-pejst tas-snien', 'the toothpaste'],
  ['il-mus tal-leħja', 'the razor'],
  ['il-miżien tal-banju', 'the bathroom scales'],
  ['il-plunger', 'the plunger'],
  ['id-deodorant', 'the deodorant'],
  ['il-hairdryer', 'the hairdryer'],
  /* beach */
  ['l-umbrella tax-xemx', 'the beach umbrella'],
  ['is-sunblock', 'the sunblock'],
  ['id-deckchair', 'the deckchair'],
  ['il-maskra tal-għads', 'the snorkel mask'],
  ['il-frisbee', 'the frisbee'],
  ['il-barmil u l-pala', 'the bucket and spade'],
  ['il-cooler box', 'the cooler box'],
  ['iż-żarbun tal-baħar', 'the sea shoes'],
  ['is-sodda tal-arja', 'the inflatable lilo'],
  /* office */
  ['l-istejpler', 'the stapler'],
  ['il-photocopier', 'the photocopier'],
  ['il-biro', 'the biro'],
  ['il-lapes', 'the pencil'],
  ['l-imqass', 'the scissors'],
  ['il-highlighter', 'the highlighter'],
  ['il-post-it', 'the sticky notes'],
  ['il-kalkulatur', 'the calculator'],
  ['il-keyboard', 'the keyboard'],
  ['il-printer', 'the printer'],
  ['is-siġġu tal-uffiċċju', 'the office swivel chair'],
  /* church */
  ['il-kuruna tar-rużarju', 'the rosary beads'],
  ['is-santa', 'the holy picture card'],
  ['ix-xemgħa', 'the candle'],
  ['l-inċens', 'the incense'],
  ['il-qanpiena', 'the church bell'],
  ['il-bank tal-knisja', 'the church pew'],
  ['l-ilma mbierek', 'the holy water'],
  /* toy box */
  ['iż-żurżieqa', 'the slide'],
  ['il-bandla', 'the swing'],
  ['il-pupa', 'the doll'],
  ['il-blokki', 'the building blocks'],
  ['ir-rota', 'the bicycle'],
  ['it-teddy bear', 'the teddy bear'],
  ['il-buzzieqa', 'the balloon'],
  ['il-gażaża', 'the dummy'],
  ['il-pram', 'the pram'],
  ['il-kuluri', 'the crayons'],
  /* nanna's front room */
  ['il-bastun', 'the walking stick'],
  ['in-nuċċali tal-qari', 'the reading glasses'],
  ['il-kaxxa tal-pilloli', 'the pill box'],
  ['il-flokk ta\' taħt', 'the vest'],
  ['ir-radju', 'the radio'],
  ['l-istanjata', 'the teapot'],
  ['il-kutra', 'the quilt'],
  ['il-papoċċ', 'the slippers'],
  ['id-dentiera', 'the false teeth'],
  ['l-album tar-ritratti', 'the photo album'],
  ['il-labar tal-knitting', 'the knitting needles'],
  ['l-inċirata', 'the plastic tablecloth'],
  /* around the house */
  ['is-sufan', 'the sofa'],
  ['is-sodda', 'the bed'],
  ['l-imħadda', 'the pillow'],
  ['il-liżar', 'the bedsheet'],
  ['il-purtiera', 'the curtain'],
  ['it-tapit', 'the carpet'],
  ['il-mera', 'the mirror'],
  ['ix-xkupa', 'the broom'],
  ['il-mopp', 'the mop'],
  ['il-barmil', 'the bucket'],
  ['l-arloġġ tal-ħajt', 'the wall clock'],
  ['l-iżveljarin', 'the alarm clock'],
  ['il-gwardarobba', 'the wardrobe'],
  ['il-kexxun tal-imbarazz', 'the junk drawer'],
  ['iċ-ċavetta', 'the front-door key'],
  ['il-magna tal-ħasil', 'the washing machine'],
  ['il-fann', 'the electric fan'],
  ['l-air conditioner', 'the air conditioner'],
  ['il-heater', 'the heater'],
  ['il-ħadida tal-mogħdija', 'the iron'],
  ['it-twavla tal-mogħdija', 'the ironing board'],
  ['il-lampa', 'the lamp'],
  ['is-swiċċ tad-dawl', 'the light switch'],
  ['il-plagg', 'the plug'],
  ['il-mus tal-but', 'the penknife'],
  ['l-umbrella', 'the umbrella'],
  ['it-termometru', 'the thermometer'],
  ['il-lajter', 'the lighter'],
  ['is-sulfarini', 'the matches'],
  ['il-batteriji', 'the AA batteries'],
  ['it-torċ', 'the torch'],
  ['il-binokli', 'the binoculars'],
  ['il-kamera', 'the camera'],
  ['il-ħabel tal-inxir', 'the washing line'],
  ['il-molol tal-inxir', 'the clothes pegs'],
  ['il-gastra', 'the flower pot'],
  ['il-gabbja tal-għasafar', 'the bird cage'],
  ['in-nassa tal-ġrieden', 'the mousetrap'],
  ['it-tapit tal-bieb', 'the welcome mat'],
  /* tech */
  ['il-mowbajl', 'the mobile phone'],
  ['it-tablet', 'the tablet'],
  ['il-laptop', 'the laptop'],
  ['ir-rimot tat-TV', 'the TV remote'],
  ['ir-router tal-wifi', 'the wifi router'],
  ['is-smartwatch', 'the smartwatch'],
  ['id-drone', 'the drone'],
  ['is-selfie stick', 'the selfie stick'],
  ['il-pendrive', 'the USB stick'],
  ['is-SIM card', 'the SIM card'],
  ['l-ispeaker', 'the bluetooth speaker'],
  /* wardrobe */
  ['iż-żarbun', 'the shoes'],
  ['il-qalziet', 'the trousers'],
  ['il-qmis', 'the shirt'],
  ['il-kalzetti', 'the odd socks'],
  ['iċ-ċinturin', 'the belt'],
  ['il-beritta', 'the beanie'],
  ['l-ingwanti', 'the gloves'],
  ['il-kappell', 'the hat'],
  ['il-ġlekk', 'the jacket'],
  ['il-malja', 'the swimsuit'],
  ['il-qalziet ta\' taħt', 'the underpants'],
  ['ir-reġipett', 'the bra'],
  /* ritual objects */
  ['il-moxt', 'the comb'],
  ['il-passaport', 'the passport'],
  ['il-karti tal-logħob', 'the playing cards'],
  ['id-dadi', 'the dice'],
  ['iċ-ċurkett', 'the ring'],
  ['il-kalendarju', 'the calendar'],
  ['ir-ritratt tat-tieġ', 'the wedding photo'],
  /* the drawer nobody opens in company — appended, never reordered,
     so the saved bag's ids stay true. 18+ app, and a filthy object
     hiding among the kettles is funnier than a shelf of them. */
  ['il-manetti bil-fer roża', 'the fluffy pink handcuffs'],
  ['il-vibratur fil-kexxun tal-kalzetti', 'the vibrator in the sock drawer'],
  ['il-lubrikant', 'the lube'],
  ['it-tanga leopard print', 'the leopard-print thong'],
  ['il-lingerie tal-Valentine\'s', 'the Valentine\'s lingerie'],
  ['ir-rivista ta\' taħt is-sodda', 'the magazine under the mattress'],
  ['il-browser history', 'the browser history'],
  ['il-pillola blu', 'the little blue pill'],
  ['it-test tat-tqala', 'the pregnancy test'],
  ['il-kondom skadut fil-kartiera', 'the expired condom in the wallet'],
  ['iż-żejt tal-massaġġi', 'the massage oil'],
  ['il-mera fuq is-saqaf', 'the mirror on the bedroom ceiling'],
  ['is-sodda li tiżżaqżaq', 'the squeaky bed'],
  ['il-bott tal-whipped cream', 'the can of whipped cream'],
  ['il-blindfold tal-ħarir', 'the silk blindfold'],
  ['l-underwear li jittiekel', 'the edible underwear'],
  ['il-kostum tal-French maid', 'the French maid costume'],
  ['il-fake tan fuq il-liżar', 'the fake tan all over the sheets'],
  ['l-ittri tal-eks fil-kaxxa taż-żraben', 'the ex\'s letters in a shoebox'],
  ['il-pole tal-fitness fis-salott', 'the "fitness" pole in the living room']
]),

/* ── MALTA — the one only this island would write ────────────────── */
th('malta', 'Malta', 'Malta', 'i-cross-malta', [
  ['il-każin tal-banda', 'the village band club'],
  ['il-festa', 'the village festa'],
  ['in-nar tal-art', 'the ground fireworks'],
  ['il-murtali', 'the festa petards'],
  ['il-marċ ta\' filgħodu', 'the morning festa march'],
  ['il-vara tal-qaddis', 'the statue of the patron saint'],
  ['il-festuni', 'the festa street decorations'],
  ['il-planċier', 'the band platform'],
  ['il-bankarella tal-qubbajt', 'the nougat stall'],
  ['il-ġostra', 'il-ġostra (the greasy pole)'],
  ['il-vapur t\'Għawdex', 'the Gozo ferry'],
  ['il-lanċa ta\' tas-Sliema', 'the Sliema ferry'],
  ['id-dgħajsa tal-pass', 'the harbour water taxi'],
  ['il-luzzu', 'the luzzu'],
  ['il-karozzin', 'the horse-drawn karozzin'],
  ['il-karozza tal-linja', 'the bus'],
  ['it-tallinja card', 'the tallinja card'],
  ['il-monti', 'the monti street market'],
  ['is-suq tal-Ħadd f\'Marsaxlokk', 'the Marsaxlokk Sunday market'],
  ['il-parkeġġ ta\' Mater Dei', 'the Mater Dei car park'],
  ['it-traffiku tal-Marsa', 'the Marsa traffic'],
  ['iċ-ċitazzjoni', 'the parking ticket'],
  ['il-qtugħ tad-dawl', 'the summer power cut'],
  ['il-gallarija', 'the Maltese balcony'],
  ['il-Belt Valletta', 'Valletta'],
  ['l-Imdina', 'Mdina'],
  ['ir-Rotunda tal-Mosta', 'the Mosta dome'],
  ['it-Tieqa tad-Dwejra', 'the Azure Window (RIP)'],
  ['il-Blue Lagoon', 'the Blue Lagoon'],
  ['Għawdex', 'Gozo'],
  ['ir-Ramla l-Ħamra', 'Ramla Bay'],
  ['is-swar tal-Belt', 'the Valletta bastions'],
  ['il-lift tal-Barrakka', 'the Barrakka lift'],
  ['Paceville', 'Paceville'],
  ['il-Karnival tan-Nadur', 'the Nadur carnival'],
  ['ir-regatta', 'the regatta'],
  ['it-tombla tal-każin', 'the Sunday tombla at the każin'],
  ['id-dar tal-lottu', 'the lotto booth'],
  ['il-pastizzeria', 'the all-night pastizzeria'],
  ['il-vann tal-ġelat', 'the ice-cream van'],
  ['tal-gass', 'the gas cylinder truck'],
  ['tal-ħobż', 'the bread van'],
  ['il-kappillan', 'the parish priest'],
  ['il-quddiesa tal-Ħadd', 'the Sunday mass'],
  ['il-knisja tal-parroċċa', 'the parish church'],
  ['il-presepju', 'the Christmas crib'],
  ['Santa Marija', 'Santa Marija week'],
  ['il-lejla tal-Eurovision', 'Eurovision night'],
  ['l-ikla tal-Ħadd għand in-nanna', 'Sunday lunch at nanna\'s'],
  ['l-Università ta\' Malta', 'the University of Malta'],
  ['l-ajruport (iċ-ċapċip mal-inżul)', 'the airport (clapping on landing)']
]),

/* ── PLACES ────────────────────────────────────────────────────── */
th('places', 'Postijiet', 'Places', 'i-map', [
  ['l-ajruport', 'the airport'],
  ['l-isptar', 'the hospital'],
  ['l-iskola', 'the school'],
  ['il-ħabs', 'the prison'],
  ['il-bank', 'the bank'],
  ['is-supermarket', 'the supermarket'],
  ['il-farmaċija', 'the pharmacy'],
  ['għand il-barbier', 'the barber shop'],
  ['is-salon tas-sbuħija', 'the beauty salon'],
  ['il-gym', 'the gym'],
  ['il-pixxina', 'the swimming pool'],
  ['il-bajja', 'the beach'],
  ['iċ-ċimiterju', 'the cemetery'],
  ['il-knisja', 'the church'],
  ['il-librerija', 'the library'],
  ['il-mużew', 'the museum'],
  ['iċ-ċinema', 'the cinema'],
  ['it-teatru', 'the theatre'],
  ['il-lunapark', 'the funfair'],
  ['iż-żu', 'the zoo'],
  ['iċ-ċirku', 'the circus'],
  ['il-casino', 'the casino'],
  ['il-lukanda', 'the hotel'],
  ['ir-ristorant', 'the restaurant'],
  ['il-bar', 'the bar'],
  ['l-istazzjon tal-petrol', 'the petrol station'],
  ['il-garaxx tal-mekkanik', 'the mechanic\'s garage'],
  ['l-uffiċċju tal-posta', 'the post office'],
  ['il-qorti', 'the courtroom'],
  ['l-għassa tal-pulizija', 'the police station'],
  ['il-fabbrika', 'the factory'],
  ['l-uffiċċju', 'the office'],
  ['ir-razzett', 'the farm'],
  ['il-foresta', 'the forest'],
  ['id-deżert', 'the desert'],
  ['il-muntanji', 'the mountains'],
  ['l-Antartika', 'Antarctica'],
  ['is-sottomarin', 'the submarine'],
  ['l-istazzjon spazjali', 'the space station'],
  ['il-cruise liner', 'the cruise ship'],
  ['l-ajruplan', 'the aeroplane'],
  ['it-tren', 'the train'],
  ['il-kastell', 'the castle'],
  ['l-università', 'the university'],
  ['is-sit tal-kostruzzjoni', 'the building site'],
  ['il-laboratorju', 'the laboratory'],
  ['għand id-dentist', 'the dentist\'s chair'],
  ['is-sala tat-tiġijiet', 'the wedding hall'],
  ['il-kindergarten', 'the kindergarten'],
  ['id-dar tal-anzjani', 'the old people\'s home'],
  ['il-camp site', 'the camp site'],
  ['il-lift', 'the lift'],
  ['it-tinda', 'the tent'],
  ['il-fanal tal-baħar', 'the lighthouse'],
  ['il-mitħna', 'the windmill'],
  ['l-għar', 'the cave'],
  ['il-vulkan', 'the volcano'],
  ['il-gżira deżerta', 'the desert island'],
  ['l-istadium tal-futbol', 'the football stadium'],
  ['il-bowling alley', 'the bowling alley'],
  ['l-escape room', 'the escape room'],
  ['il-launderette', 'the launderette'],
  ['iċ-ċentru kummerċjali', 'the shopping mall']
]),

/* ── FOOD & DRINK ──────────────────────────────────────────────── */
th('food', 'Ikel u Xorb', 'Food & Drink', 'sp-fork', [
  ['il-pastizz', 'the pastizz'],
  ['il-ħobż biż-żejt', 'il-ħobż biż-żejt'],
  ['il-ħobża Maltija', 'the crusty Maltese loaf'],
  ['il-ftira', 'the ftira'],
  ['it-timpana', 'the timpana'],
  ['ir-ross il-forn', 'the baked rice'],
  ['il-fenek moqli', 'the fried rabbit'],
  ['il-braġjoli', 'the braġjoli (beef olives)'],
  ['it-torta tal-lampuki', 'the lampuki pie'],
  ['l-aljotta', 'the aljotta fish soup'],
  ['is-soppa tal-armla', 'the widow\'s soup'],
  ['il-kusksu', 'il-kusksu (the bean soup)'],
  ['il-minestra', 'the minestra'],
  ['il-brodu', 'the broth'],
  ['il-bigilla', 'the bigilla'],
  ['iz-zalzett Malti', 'the Maltese sausage'],
  ['il-ġbejniet', 'the ġbejniet'],
  ['il-galletti', 'the galletti crackers'],
  ['iż-żebbuġ', 'the olives'],
  ['il-kappar', 'the capers'],
  ['it-tadam imqadded', 'the sun-dried tomatoes'],
  ['il-laħam taż-żiemel', 'the horsemeat'],
  ['l-imqaret', 'the imqaret'],
  ['il-qubbajt', 'the festa nougat'],
  ['il-kannoli', 'the kannoli'],
  ['il-figolla', 'the Easter figolla'],
  ['il-prinjolata', 'the prinjolata'],
  ['il-kwareżimal', 'the kwareżimal'],
  ['il-pizza', 'the pizza'],
  ['il-burger', 'the burger'],
  ['iċ-ċips', 'the chips'],
  ['il-kebab', 'the kebab'],
  ['is-sushi', 'the sushi'],
  ['l-ispagetti', 'the spaghetti'],
  ['il-froġa', 'the omelette'],
  ['il-bajd u l-bejken', 'the eggs and bacon'],
  ['il-pancakes', 'the pancakes'],
  ['l-avocado toast', 'the avocado toast'],
  ['il-hot dog', 'the hot dog'],
  ['iċ-ċikkulata', 'the chocolate'],
  ['il-ġelat', 'the ice cream'],
  ['id-dulliegħa', 'the watermelon'],
  ['l-insalata', 'the salad'],
  ['iz-zalza tat-tadam', 'the tomato sauce'],
  ['il-ġobon', 'the cheese'],
  ['il-ħalib', 'the milk'],
  ['il-ħut moqli', 'the fried fish'],
  ['il-majjal il-forn', 'the roast pork'],
  ['id-dundjan tal-Milied', 'the Christmas turkey'],
  ['il-mixwi', 'the barbecue'],
  ['il-kafè', 'the coffee'],
  ['it-te', 'the tea'],
  ['il-birra', 'the beer'],
  ['l-inbid', 'the wine'],
  ['il-whisky', 'the whisky'],
  ['il-luminata', 'the fizzy drink'],
  ['l-ilma tal-flixkun', 'the bottled water']
]),

/* ── SPORTS ────────────────────────────────────────────────────── */
th('sports', 'Sports', 'Sports', 'sp-ball', [
  ['il-futbol', 'football'],
  ['il-waterpolo', 'waterpolo'],
  ['il-boċċi', 'boċċi'],
  ['it-tennis', 'tennis'],
  ['il-padel', 'padel'],
  ['il-basketball', 'basketball'],
  ['il-volleyball', 'volleyball'],
  ['ir-rugby', 'rugby'],
  ['il-golf', 'golf'],
  ['is-snooker', 'snooker'],
  ['il-biljard tal-bar', 'bar pool'],
  ['id-darts', 'darts'],
  ['iċ-ċikliżmu', 'cycling'],
  ['il-marathon', 'the marathon'],
  ['l-għawm', 'swimming'],
  ['l-għads', 'scuba diving'],
  ['is-sajd', 'fishing'],
  ['l-irkib taż-żwiemel', 'horse riding'],
  ['it-tiġrijiet taż-żwiemel', 'the horse races'],
  ['il-boxing', 'boxing'],
  ['il-karate', 'karate'],
  ['il-ġinnastika', 'gymnastics'],
  ['l-irfigħ tal-piżijiet', 'weightlifting'],
  ['iċ-ċess', 'chess'],
  ['il-ping pong', 'ping pong'],
  ['il-badminton', 'badminton'],
  ['l-iskiing', 'skiing'],
  ['l-iskating fuq is-silġ', 'ice skating'],
  ['is-surfing', 'surfing'],
  ['il-kayaking', 'kayaking'],
  ['it-tbaħħir', 'sailing'],
  ['l-iskrima', 'fencing'],
  ['l-archery', 'archery'],
  ['il-paintball', 'paintball'],
  ['il-go-karts', 'go-karting'],
  ['iż-żfin tas-sala', 'ballroom dancing'],
  ['il-yoga', 'yoga'],
  ['il-crossfit', 'crossfit'],
  ['il-Formula 1', 'Formula 1'],
  ['il-wrestling', 'wrestling'],
  ['is-sumo', 'sumo'],
  ['il-cricket', 'cricket'],
  ['il-baseball', 'baseball'],
  ['l-American football', 'American football'],
  ['il-handball', 'handball']
]),

/* ── JOBS ──────────────────────────────────────────────────────── */
th('jobs', 'Xogħlijiet', 'Jobs', 'sp-case', [
  ['it-tabib', 'the doctor'],
  ['l-infermiera', 'the nurse'],
  ['id-dentist', 'the dentist'],
  ['l-għalliem', 'the teacher'],
  ['il-pulizija', 'the police officer'],
  ['is-suldat', 'the soldier'],
  ['il-bdot', 'the pilot'],
  ['l-air hostess', 'the flight attendant'],
  ['is-sewwieq tal-linja', 'the bus driver'],
  ['is-sewwieq tat-taxi', 'the taxi driver'],
  ['il-courier tal-ikel', 'the food courier'],
  ['il-barbier', 'the barber'],
  ['il-parrukkiera', 'the hairdresser'],
  ['il-kok', 'the chef'],
  ['il-wejter', 'the waiter'],
  ['il-barman', 'the barman'],
  ['is-sajjied', 'the fisherman'],
  ['il-bidwi', 'the farmer'],
  ['il-bennej', 'the bricklayer'],
  ['il-mastrudaxxa', 'the carpenter'],
  ['il-plumber', 'the plumber'],
  ['l-elettriċista', 'the electrician'],
  ['il-mekkanik', 'the mechanic'],
  ['il-pittur', 'the painter'],
  ['l-iskarpan', 'the cobbler'],
  ['il-ħajjata', 'the seamstress'],
  ['l-avukat', 'the lawyer'],
  ['l-imħallef', 'the judge'],
  ['in-nutar', 'the notary'],
  ['il-perit', 'the architect'],
  ['l-ispiżjar', 'the pharmacist'],
  ['il-veterinarju', 'the vet'],
  ['ix-xjenzat', 'the scientist'],
  ['l-astronawta', 'the astronaut'],
  ['il-qassis', 'the priest'],
  ['is-soru', 'the nun'],
  ['il-ħaffier tal-oqbra', 'the gravedigger'],
  ['il-gwardjan tas-sigurtà', 'the security guard'],
  ['il-bouncer', 'the bouncer'],
  ['il-warden', 'the traffic warden'],
  ['il-politiku', 'the politician'],
  ['il-ġurnalist', 'the journalist'],
  ['il-fotografu', 'the photographer'],
  ['l-attur', 'the actor'],
  ['il-kantant', 'the singer'],
  ['id-DJ', 'the DJ'],
  ['l-influencer', 'the influencer'],
  ['il-lifeguard', 'the lifeguard'],
  ['il-pustier', 'the postman'],
  ['il-programmatur', 'the programmer'],
  ['l-accountant', 'the accountant'],
  ['it-tattoo artist', 'the tattoo artist'],
  ['il-buffu taċ-ċirku', 'the circus clown']
]),

/* ── FILMS & TV — titles and characters as answers, nothing more ── */
th('screen', 'Films u TV', 'Films & TV', 'sp-tv', [
  ['Harry Potter', 'Harry Potter'],
  ['James Bond', 'James Bond'],
  ['Batman', 'Batman'],
  ['Superman', 'Superman'],
  ['Spider-Man', 'Spider-Man'],
  ['Shrek', 'Shrek'],
  ['The Simpsons', 'The Simpsons'],
  ['SpongeBob', 'SpongeBob'],
  ['Titanic', 'Titanic'],
  ['Jaws', 'Jaws'],
  ['Jurassic Park', 'Jurassic Park'],
  ['Star Wars', 'Star Wars'],
  ['Rocky', 'Rocky'],
  ['Rambo', 'Rambo'],
  ['Terminator', 'Terminator'],
  ['The Godfather', 'The Godfather'],
  ['Mr. Bean', 'Mr. Bean'],
  ['Friends', 'Friends'],
  ['Game of Thrones', 'Game of Thrones'],
  ['Breaking Bad', 'Breaking Bad'],
  ['Stranger Things', 'Stranger Things'],
  ['Squid Game', 'Squid Game'],
  ['Money Heist', 'Money Heist'],
  ['The Office', 'The Office'],
  ['Peppa Pig', 'Peppa Pig'],
  ['Tom u Jerry', 'Tom and Jerry'],
  ['Mickey Mouse', 'Mickey Mouse'],
  ['Ċindirella', 'Cinderella'],
  ['Frozen', 'Frozen'],
  ['The Lion King', 'The Lion King'],
  ['Pirates of the Caribbean', 'Pirates of the Caribbean'],
  ['Home Alone', 'Home Alone'],
  ['Grease', 'Grease'],
  ['The Sound of Music', 'The Sound of Music'],
  ['Avatar', 'Avatar'],
  ['Dracula', 'Dracula'],
  ['Big Brother', 'Big Brother'],
  ['Love Island', 'Love Island'],
  ['MasterChef', 'MasterChef'],
  ['X Factor', 'X Factor'],
  ['Xarabank', 'Xarabank'],
  ['it-teleserje Maltija', 'the Maltese teleserje'],
  ['l-aħbarijiet tat-tmienja', 'the eight o\'clock news']
]),

/* ── ANIMALS ───────────────────────────────────────────────────── */
th('animals', 'Annimali', 'Animals', 'sp-paw', [
  ['il-kelb', 'the dog'],
  ['il-qattus', 'the cat'],
  ['il-fenek', 'the rabbit'],
  ['iż-żiemel', 'the horse'],
  ['il-ħmar', 'the donkey'],
  ['il-baqra', 'the cow'],
  ['il-mogħża', 'the goat'],
  ['in-nagħġa', 'the sheep'],
  ['il-ħanżir', 'the pig'],
  ['is-serduq', 'the rooster'],
  ['it-tiġieġa', 'the hen'],
  ['il-papra', 'the duck'],
  ['il-gawwija', 'the seagull'],
  ['il-ħamiema', 'the pigeon'],
  ['il-kanarin', 'the canary'],
  ['il-pappagall', 'the parrot'],
  ['il-barbaġann', 'the owl'],
  ['il-farfett', 'the butterfly'],
  ['in-naħla', 'the bee'],
  ['in-nemla', 'the ant'],
  ['il-brimba', 'the spider'],
  ['il-wirdiena', 'the cockroach'],
  ['in-nemusa', 'the mosquito'],
  ['id-dubbiena', 'the fly'],
  ['il-bebbuxu', 'the snail'],
  ['il-gremxula', 'the lizard'],
  ['il-wiżgħa', 'the house gecko'],
  ['is-serp', 'the snake'],
  ['il-fekruna', 'the tortoise'],
  ['il-ġurdien', 'the mouse'],
  ['il-far', 'the rat'],
  ['il-farfett il-lejl', 'the bat'],
  ['id-delfin', 'the dolphin'],
  ['il-kelb il-baħar', 'the shark'],
  ['il-qarnita', 'the octopus'],
  ['il-lampuka', 'the lampuka'],
  ['l-awwista', 'the lobster'],
  ['ir-rizza', 'the sea urchin'],
  ['il-bram', 'the jellyfish'],
  ['l-iljun', 'the lion'],
  ['it-tigra', 'the tiger'],
  ['l-iljunfant', 'the elephant'],
  ['il-ġiraffa', 'the giraffe'],
  ['ix-xadina', 'the monkey'],
  ['iż-żebra', 'the zebra'],
  ['il-kangarù', 'the kangaroo'],
  ['il-pingwin', 'the penguin'],
  ['l-ors', 'the bear'],
  ['il-kukkudrill', 'the crocodile'],
  ['il-ġemel', 'the camel']
]),

/* ── BRANDS — answers in a word game; nominative use only ───────── */
th('brands', 'Ditti', 'Brands', 'sp-tag', [
  ['il-Kinnie', 'Kinnie'],
  ['iċ-Ċisk', 'Cisk'],
  ['it-Twistees', 'Twistees'],
  ['il-Farsons', 'Farsons'],
  ['il-Benna', 'Benna'],
  ['il-Pavi', 'Pavi'],
  ['il-Pama', 'Pama'],
  ['il-Lidl', 'Lidl'],
  ['il-Welbee\'s', 'Welbee\'s'],
  ['il-GO', 'GO'],
  ['il-Melita', 'Melita'],
  ['l-Epic', 'Epic'],
  ['il-Maltapost', 'Maltapost'],
  ['l-Air Malta', 'Air Malta'],
  ['il-BOV', 'BOV'],
  ['l-HSBC', 'HSBC'],
  ['il-Bolt', 'Bolt'],
  ['il-Wolt', 'Wolt'],
  ['l-eCabs', 'eCabs'],
  ['ir-Ryanair', 'Ryanair'],
  ['il-Coca-Cola', 'Coca-Cola'],
  ['il-Pepsi', 'Pepsi'],
  ['il-Fanta', 'Fanta'],
  ['ir-Red Bull', 'Red Bull'],
  ['il-McDonald\'s', 'McDonald\'s'],
  ['il-Burger King', 'Burger King'],
  ['il-KFC', 'KFC'],
  ['is-Subway', 'Subway'],
  ['l-iStarbucks', 'Starbucks'],
  ['in-Nutella', 'Nutella'],
  ['il-Kinder', 'Kinder'],
  ['in-Nescafé', 'Nescafé'],
  ['il-Lipton', 'Lipton'],
  ['il-Heineken', 'Heineken'],
  ['il-Guinness', 'Guinness'],
  ['in-Nike', 'Nike'],
  ['l-Adidas', 'Adidas'],
  ['il-Puma', 'Puma'],
  ['iz-Zara', 'Zara'],
  ['l-H&M', 'H&M'],
  ['ix-Shein', 'Shein'],
  ['it-Temu', 'Temu'],
  ['il-Gucci', 'Gucci'],
  ['ir-Rolex', 'Rolex'],
  ['l-IKEA', 'IKEA'],
  ['l-Apple', 'Apple'],
  ['is-Samsung', 'Samsung'],
  ['in-Nokia l-antika', 'the old Nokia brick'],
  ['il-PlayStation', 'PlayStation'],
  ['l-Xbox', 'Xbox'],
  ['in-Nintendo', 'Nintendo'],
  ['in-Netflix', 'Netflix'],
  ['l-iSpotify', 'Spotify'],
  ['il-YouTube', 'YouTube'],
  ['it-TikTok', 'TikTok'],
  ['l-Instagram', 'Instagram'],
  ['il-Facebook', 'Facebook'],
  ['il-WhatsApp', 'WhatsApp'],
  ['il-Google', 'Google'],
  ['l-Amazon', 'Amazon'],
  ['it-Tesla', 'Tesla'],
  ['il-Ferrari', 'Ferrari'],
  ['it-Toyota', 'Toyota'],
  ['il-Lego', 'Lego'],
  ['il-Barbie', 'Barbie'],
  ['il-Monopoly', 'Monopoly'],
  ['il-Colgate', 'Colgate'],
  ['in-Nivea', 'Nivea'],
  ['id-Dettol', 'Dettol'],
  ['il-Fairy', 'Fairy'],
  ['il-WD-40', 'WD-40'],
  ['l-UHU', 'UHU'],
  ['il-Bic', 'Bic'],
  ['il-Casio', 'Casio'],
  ['il-Crocs', 'Crocs'],
  ['id-Durex', 'Durex'],
  ['il-Jägermeister', 'Jägermeister']
]),

/* ── AFTER MIDNIGHT — the 18+ shelf of the 18+ app ──────────────── */
th('night', 'Wara Nofsillejl', 'After Midnight', 'sp-moon', [
  ['ix-shot tat-tequila', 'the tequila shot'],
  ['ir-round tax-shots', 'the round of shots'],
  ['il-hangover', 'the hangover'],
  ['il-kebab tal-erbgħa ta\' filgħodu', 'the 4 a.m. kebab'],
  ['it-taxi tal-lejl', 'the ride home'],
  ['il-happy hour', 'the happy hour'],
  ['il-karaoke', 'the karaoke'],
  ['l-istrip club', 'the strip club'],
  ['il-bachelor\'s', 'the stag night'],
  ['il-hen party', 'the hen party'],
  ['it-Tinder', 'Tinder'],
  ['il-ghosting', 'the ghosting'],
  ['il-one night stand', 'the one night stand'],
  ['il-walk of shame', 'the walk of shame'],
  ['il-friend zone', 'the friend zone'],
  ['l-ex', 'the ex'],
  ['il-flirting', 'the flirting'],
  ['id-dance floor', 'the dance floor'],
  ['il-VIP area', 'the VIP area'],
  ['il-fake ID', 'the fake ID'],
  ['il-beer pong', 'the beer pong'],
  ['il-vape', 'the vape'],
  ['is-sigarett imsellef', 'the borrowed cigarette'],
  ['ix-xampanja', 'the champagne'],
  ['il-cocktail', 'the cocktail'],
  ['l-aħħar rawnd', 'the last round'],
  ['il-kondom', 'the condom'],
  ['is-sugar daddy', 'the sugar daddy'],
  ['il-love bite', 'the love bite'],
  ['l-afterparty', 'the afterparty'],
  ['ir-request lid-DJ', 'the song request to the DJ'],
  ['il-kju tat-tojlit', 'the toilet queue'],
  ['il-messaġġ fis-sakra', 'the drunk text'],
  ['il-body shot', 'the body shot'],
  ['il-lap dance', 'the lap dance'],
  ['it-truth or dare', 'truth or dare'],
  /* appended — the ids above are in saved bags and must not move */
  ['il-pre-drinks', 'the pre-drinks'],
  ['il-boat party ta\' Kemmuna', 'the Comino boat party'],
  ['il-Jägerbomb', 'the Jägerbomb'],
  ['ix-shot tas-sambuca bin-nar', 'the flaming sambuca shot'],
  ['iċ-chaser tal-Kinnie', 'the Kinnie chaser'],
  ['il-pub crawl', 'the pub crawl'],
  ['iż-żfin fuq il-mejda', 'dancing on the table'],
  ['il-bewsa ma\' barrani', 'the kiss with a total stranger'],
  ['in-numru miktub fuq l-id', 'the phone number written on a hand'],
  ['il-ħabib li jibki fis-sakra', 'the friend who cries when drunk'],
  ['il-ħabiba l-ġdida tat-tojlit', 'the new best friend from the club toilets'],
  ['il-mixja ħafja bil-heels f\'idejk', 'the barefoot walk, heels in hand'],
  ['it-tattoo tas-sakra', 'the drunk tattoo'],
  ['il-karta li ma għaddietx il-bar', 'the card declined at the bar'],
  ['it-tmintax-il missed call tal-mamà', 'the eighteen missed calls from mum'],
  ['l-għawma għarwien f\'nofs ta\' lejl', 'the midnight skinny dip'],
  ['il-lock-in fil-bar tar-raħal', 'the village bar lock-in'],
  ['l-open bar tat-tieġ', 'the wedding open bar'],
  ['il-karozza li raqdet Paceville', 'the car that slept in Paceville'],
  ['il-bachelor\'s f\'Amsterdam', 'the Amsterdam stag trip'],
  ['l-istripper tal-hen', 'the hen party stripper'],
  ['l-istrip poker', 'the strip poker'],
  ['in-Never Have I Ever', 'the game of Never Have I Ever'],
  ['l-ispin the bottle', 'the spin the bottle'],
  ['il-friends with benefits', 'the friends with benefits'],
  ['il-booty call', 'the booty call'],
  ['is-sexting', 'the sexting'],
  ['is-safe word', 'the safe word'],
  ['il-quickie', 'the quickie'],
  ['id-designated driver', 'the designated driver']
]),

/* ── THE MORNING AFTER — the reckoning ──────────────────────────────
   Wara Nofsillejl is the night; this is the bill. A separate seam on
   purpose: the questions are different ("how do you feel", "who do
   you call", "what does it cost") and every entry is a situation the
   spy has to bluff through, not a body part. 18+, same as night. */
th('morning', 'L-Għada Filgħodu', 'The Morning After', 'sp-sun', [
  ['il-hangxiety', 'the hangxiety'],
  ['il-memorja vojta tal-bieraħ', 'the blank where last night should be'],
  ['l-iscroll tal-biża\' fil-messaġġi', 'the terrified scroll through sent messages'],
  ['in-numru salvat bħala "???"', 'the contact saved as "???"'],
  ['il-pastizzi tal-fejqan', 'the recovery pastizzi'],
  ['iż-żarbuna li għebet', 'the shoe that never came home'],
  ['il-flixkun ilma ħdejn is-sodda', 'the bedside pint of water'],
  ['is-sodda ta\' ħaddieħor', 'somebody else\'s bed'],
  ['in-notifika tal-bank tat-tmienja', 'the 8 a.m. bank notification'],
  ['ir-Revolut request ta\' sħabek', 'the Revolut request from the lads'],
  ['il-hoodie li mhux tiegħek', 'the hoodie that is not yours'],
  ['il-quddiesa tal-Ħadd bil-hangover', 'Sunday mass on a hangover'],
  ['ir-ritratti mhux mistennija fil-gallery', 'the surprise photos in the gallery'],
  ['l-istory li trid titħassar malajr', 'the story that must come down before work'],
  ['l-apoloġija fil-group chat', 'the apology to the group chat'],
  ['il-vuċi mitlufa mill-karaoke', 'the voice lost to the karaoke'],
  ['it-tbenġila misterjuża', 'the mystery bruise'],
  ['it-timbru tal-klabb li ma jitlaqx', 'the club stamp that will not wash off'],
  ['il-glitter li jibqa\' ġimgħa', 'the glitter that stays a week'],
  ['is-sebħ fuq Paceville', 'sunrise over Paceville'],
  ['il-wegħda li qatt mhu se terġa\' tixrob', 'the solemn vow never to drink again'],
  ['in-nofs kebab fuq il-komodina', 'the half kebab on the nightstand'],
  ['il-morning after pill', 'the morning-after pill'],
  ['il-lift ta\' filgħodu mingħand il-papà', 'the silent lift home from dad']
]);

let total = 0;
for (const t of T) total += t.words.length;

window.KARTI_SPY_WORDS = {
  version: 1,
  themes: T,
  total,
  theme: id => T.find(t => t.id === id) || null
};

})();
