/* crypt-2
   GENERATED by tools/mkdungeon.py — regenerate rather than hand-edit.
   The Sunken Crypt, room 2 of 4 (alcoves). The Cistern */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['crypt-2'] = {
  id: 'crypt-2', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [5,2,1,3,1,2,1,1,5,2],
    [3,1,2,1,1,5,2,1,3,1],
    [1,1,5,2,1,3,1,2,1,1],
    [2,1,3,1,2,1,1,5,2,1],
    [1,2,1,1,5,2,1,3,1,2],
    [1,5,2,1,3,1,2,1,1,5],
    [1,3,1,2,1,1,5,2,1,3],
    [2,1,1,5,2,1,3,1,2,1],
    [5,2,1,3,1,2,1,1,5,2],
    [3,1,2,1,1,5,2,1,3,1]
  ],
  decor: [
    [8,8,8,8,9,8,8,8,8,8],
    [8,0,0,10,12,0,10,0,13,8],
    [8,0,0,10,0,0,10,0,0,8],
    [9,0,0,0,0,0,0,0,0,8],
    [8,0,0,0,0,0,0,0,0,8],
    [11,0,0,0,0,0,0,0,0,11],
    [8,0,0,0,0,0,0,0,0,9],
    [8,0,10,0,0,0,0,10,0,8],
    [8,14,10,0,0,12,0,10,0,8],
    [8,8,8,8,8,8,9,8,8,8]
  ],
  block: [
    [1,1,1,1,1,1,1,1,1,1],
    [1,0,0,1,1,0,1,0,1,1],
    [1,0,0,1,0,0,1,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,1,0,0,0,0,1,0,1],
    [1,1,1,0,0,1,0,1,0,1],
    [1,1,1,1,1,1,1,1,1,1]
  ],
  markers: [
    { type:'fight', id:'crypt-fight-2', name:'The Cistern', c:5, r:3, sprite:'skelarcher', dir:'SW', foes:['grunt', 'archer', 'gecko'] },
    { type:'exit', c:0, r:5, to:'crypt-1', at:{ c:8, r:5 } },
    { type:'exit', c:9, r:5, to:'crypt-3', at:{ c:1, r:5 } }
  ],
  /* joined by DOORS, not by edges — a dungeon has no seam to get wrong */
  neighbours: { n:null, e:null, s:null, w:null }
};
