/* crypt-4
   GENERATED by tools/mkdungeon.py — regenerate rather than hand-edit.
   The Sunken Crypt, room 4 of 4 (open). The Drowned Warden — THE BOSS ROOM. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['crypt-4'] = {
  id: 'crypt-4', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [1,3,1,2,1,1,5,2,1,3],
    [2,1,1,5,2,1,3,1,2,1],
    [5,2,1,3,1,2,1,1,5,2],
    [3,1,2,1,1,5,2,1,3,1],
    [1,1,5,2,1,3,1,2,1,1],
    [2,1,3,1,2,1,1,5,2,1],
    [1,2,1,1,5,2,1,3,1,2],
    [1,5,2,1,3,1,2,1,1,5],
    [1,3,1,2,1,1,5,2,1,3],
    [2,1,1,5,2,1,3,1,2,1]
  ],
  decor: [
    [8,8,8,8,9,8,8,8,8,8],
    [8,12,10,0,0,0,0,10,12,8],
    [8,0,0,0,0,0,0,0,0,8],
    [9,0,0,0,0,0,0,0,0,8],
    [8,0,0,0,0,0,0,0,0,8],
    [11,0,0,0,0,0,0,0,0,8],
    [8,0,0,0,0,0,0,0,0,9],
    [8,0,0,0,0,0,0,0,0,8],
    [8,12,10,0,0,0,0,10,12,8],
    [8,8,8,8,8,8,9,8,8,8]
  ],
  block: [
    [1,1,1,1,1,1,1,1,1,1],
    [1,1,1,0,0,0,0,1,1,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,1,1,0,0,0,0,1,1,1],
    [1,1,1,1,1,1,1,1,1,1]
  ],
  markers: [
    { type:'fight', id:'crypt-fight-4', name:'The Drowned Warden', c:5, r:3, sprite:'skeleton', dir:'SW', foes:['warden_boss', 'grunt', 'grunt'], boss:'sunken-crypt' },
    { type:'exit', c:0, r:5, to:'crypt-3', at:{ c:8, r:5 } }
  ],
  /* joined by DOORS, not by edges — a dungeon has no seam to get wrong */
  neighbours: { n:null, e:null, s:null, w:null }
};
