/* field-2-2 — beginner overworld screen (2,2) of a 5x3 grid.
   GENERATED by slicing one 46x28 global grid into 10x10 screens with a
   one-tile overlap (Dofus screen model: every map is the same size and is
   framed whole), so every edge shared with a neighbour is the SAME strip
   of world and is identical in ground/decor/block by construction.
   Pure data — regenerate rather than hand-edit seams. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-2-2'] = {
  id: 'field-2-2', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [16,16,17,16,20,16,16,16,17,18],
    [16,16,16,16,20,16,17,16,16,16],
    [21,21,21,16,20,17,16,17,16,18],
    [21,21,21,16,20,16,16,16,16,16],
    [16,16,16,16,20,16,16,16,16,16],
    [18,16,16,17,20,16,16,16,16,16],
    [20,20,20,20,20,20,20,20,20,20],
    [17,16,16,16,16,16,17,16,16,17],
    [16,16,17,16,16,16,16,17,17,16],
    [21,21,21,21,21,21,21,21,21,21]
  ],
  decor: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,25,0,30,0,0],
    [0,30,26,24,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,24,0,0,26,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  block: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [1,1,1,0,0,0,0,0,0,0],
    [1,1,1,0,0,1,0,0,0,0],
    [0,0,1,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,1,0,0,1,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [1,1,1,1,1,1,1,1,1,1]
  ],
  markers: [

  ],
  neighbours: { n:"field-2-1", e:"field-3-2", s:null, w:"field-1-2" }
};
