/* field-0-1 — beginner overworld screen (0,1) of a 5x3 grid.
   GENERATED by slicing one 46x28 global grid into 10x10 screens with a
   one-tile overlap (Dofus screen model: every map is the same size and is
   framed whole), so every edge shared with a neighbour is the SAME strip
   of world and is identical in ground/decor/block by construction.
   Pure data — regenerate rather than hand-edit seams. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-0-1'] = {
  id: 'field-0-1', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [21,16,16,16,16,16,17,20,16,16],
    [21,16,16,18,16,18,16,20,16,16],
    [21,16,16,16,16,16,16,20,16,16],
    [21,16,17,17,16,17,17,20,16,16],
    [21,22,16,18,16,16,18,20,16,17],
    [21,16,16,16,16,18,16,20,16,18],
    [21,16,16,16,17,16,16,20,16,16],
    [21,16,16,16,16,16,16,20,18,17],
    [21,16,16,17,16,16,16,20,16,16],
    [21,16,16,16,16,16,16,20,16,16]
  ],
  decor: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,24,0,24,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,30,0,24,0,0,0,24,24],
    [0,0,0,0,0,24,24,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,24],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,30,24,0,0,0,0]
  ],
  block: [
    [1,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [1,0,1,0,1,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [1,1,0,0,1,0,0,0,1,1],
    [1,0,0,0,0,1,1,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,1,0,0,0,0]
  ],
  markers: [

  ],
  neighbours: { n:"field-0-0", e:"field-1-1", s:"field-0-2", w:null }
};
