/* field-1-1 — beginner overworld screen (1,1) of a 5x3 grid.
   GENERATED by slicing one 46x28 global grid into 10x10 screens with a
   one-tile overlap (Dofus screen model: every map is the same size and is
   framed whole), so every edge shared with a neighbour is the SAME strip
   of world and is identical in ground/decor/block by construction.
   Pure data — regenerate rather than hand-edit seams. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-1-1'] = {
  id: 'field-1-1', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [16,17,16,17,16,16,16,16,18,16],
    [16,16,17,18,16,16,16,17,16,17],
    [16,16,17,17,16,17,16,16,16,16],
    [16,16,17,18,17,16,16,16,16,16],
    [17,18,16,16,16,16,16,17,16,16],
    [18,16,16,16,16,16,17,16,16,16],
    [16,16,17,16,16,16,18,18,16,16],
    [17,16,16,16,17,16,16,17,17,16],
    [16,16,17,18,16,16,16,17,16,18],
    [16,16,16,18,16,16,16,16,18,16]
  ],
  decor: [
    [0,0,0,0,0,0,0,24,0,24],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [24,0,0,0,0,0,26,0,0,0],
    [0,0,0,25,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,24],
    [24,0,0,0,24,0,0,25,0,0],
    [0,0,25,0,0,0,0,0,0,0],
    [0,0,24,0,0,0,0,0,0,0]
  ],
  block: [
    [0,0,0,0,0,0,0,1,0,1],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,1,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,1,0,0,1,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0]
  ],
  markers: [
    { type:"fight", id:"woolly-1", name:"Wild Woolly", c:3, r:2, sprite:"sheep", dir:"S", foes:["sheep", "goat"] }
  ],
  neighbours: { n:"field-1-0", e:"field-2-1", s:"field-1-2", w:"field-0-1" }
};
