/* field-3-6 — Wayrest. Level 1 country.
   GENERATED by tools/mkworld.py: one island is drawn whole, then cut into
   screens, so every seam is the SAME strip of world by construction.
   Regenerate rather than hand-editing. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-3-6'] = {
  id: 'field-3-6', w: 10, h: 10, atlas: 'art/world.png',
  /* THE PAINTED-MAP PILOT (ISLAND_DESIGN.md "maps are PAINTINGS").
     One illustration replaces the drawn ground+decor; it was generated
     from this map's own blockout template (tools/blockout.py --map
     field-3-6), so the art agrees with block[][] by construction.
     block/markers/neighbours below still rule walkability, untouched.
     NOTE for regeneration: mkworld.py does not know this key yet — if
     the world is regenerated, re-add `bg` here. */
  bg: 'art/bg/field-3-6.jpg',
  ground: [
    [20,20,20,20,20,20,20,16,20,16],
    [20,20,20,20,20,20,20,20,20,20],
    [20,20,20,20,20,20,20,20,20,20],
    [19,20,20,20,20,20,16,19,19,19],
    [20,20,20,20,20,20,20,19,19,19],
    [20,20,20,20,20,20,20,19,19,19],
    [20,20,20,20,20,20,20,19,19,19],
    [16,20,20,20,20,20,20,20,20,20],
    [19,20,20,20,20,20,19,19,19,19],
    [20,20,20,20,20,20,20,20,19,19]
  ],
  decor: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,26,25,26],
    [0,0,0,0,0,0,0,26,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,26,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  block: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,1,1],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  markers: [
    /* THE TAVERN KEEPER, on the square in Wayrest. He gives the crypt
       quest, sells the keys, bread and potions, and the tavern is where
       the chat room will live. */
    { type:'npc', id:'keeper', name:'Sula the Keeper', c:2, r:2 }
  ],
  neighbours: { n:'field-3-5', e:'field-4-6', s:'field-3-7', w:'field-2-6' }
};
