/* field-2-7 — The Necropolis. Level 12 country.
   GENERATED by tools/mkworld.py: one island is drawn whole, then cut into
   screens, so every seam is the SAME strip of world by construction.
   Regenerate rather than hand-editing. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-2-7'] = {
  id: 'field-2-7', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [19,19,19,19,19,19,19,19,19,20],
    [19,19,19,19,17,19,19,19,20,19],
    [19,20,17,19,19,17,20,17,19,19],
    [19,19,17,17,19,19,20,17,20,20],
    [19,19,20,19,20,20,20,19,19,17],
    [20,20,19,19,19,17,19,17,17,17],
    [19,19,19,20,19,19,19,19,19,17],
    [19,19,19,19,19,19,19,20,17,20],
    [20,19,19,19,20,19,19,20,19,20],
    [19,20,19,19,20,20,19,19,20,19]
  ],
  decor: [
    [26,0,0,26,0,26,0,26,0,0],
    [26,0,0,26,0,26,0,26,0,0],
    [0,0,26,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,26,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,26,0,0,31,0,0,0,0],
    [0,0,0,0,0,0,26,26,0,0],
    [0,0,0,29,26,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  block: [
    [1,0,0,1,0,1,0,1,0,0],
    [1,0,0,1,0,1,0,1,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,1,0,0],
    [0,0,0,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  markers: [
{ type:'fight', id:'necro-2-7', name:'The Necropolis', c:3, r:3, sprite:'skeleton', dir:'SW', foes:['grunt', 'archer', 'mage'] },
    /* The Necropolis — level-gated dungeon mouth. */
    { type:'exit', c:5, r:5, to:'necro-1', at:{ c:1, r:5 }, need:25, dungeon:'necropolis',
      name:'The Necropolis' }
  ],
  neighbours: { n:'field-2-6', e:'field-3-7', s:'field-2-8', w:'field-1-7' }
};
