/* field-4-0 — beginner overworld screen (4,0) of a 5x3 grid.
   GENERATED by slicing one 46x28 global grid into 10x10 screens with a
   one-tile overlap (Dofus screen model: every map is the same size and is
   framed whole), so every edge shared with a neighbour is the SAME strip
   of world and is identical in ground/decor/block by construction.
   Pure data — regenerate rather than hand-edit seams. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-4-0'] = {
  id: 'field-4-0', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [21,21,21,21,21,21,21,21,21,21],
    [16,16,22,16,17,22,22,16,22,21],
    [16,16,16,17,17,16,16,16,22,21],
    [16,16,16,17,16,17,16,16,22,21],
    [16,16,18,17,17,16,17,17,16,21],
    [16,17,16,16,18,16,17,16,18,21],
    [20,20,20,16,16,16,16,16,16,21],
    [16,16,20,16,16,16,17,16,22,21],
    [18,16,20,16,16,16,16,16,16,21],
    [16,17,20,16,17,18,17,17,16,21]
  ],
  decor: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,24,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,24,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  block: [
    [1,1,1,1,1,1,1,1,1,1],
    [0,0,1,0,0,1,1,0,1,1],
    [0,0,0,0,0,0,0,0,1,1],
    [0,0,0,0,0,0,0,0,1,1],
    [0,0,0,0,0,0,0,0,0,1],
    [0,0,1,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,1,0,0,1,1],
    [0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,0,1]
  ],
  markers: [

  ],
  neighbours: { n:null, e:null, s:"field-4-1", w:"field-3-0" }
};
