/* field-2-1 — The Terraces. Level 2 country.
   GENERATED by tools/mkworld.py: one island is drawn whole, then cut into
   screens, so every seam is the SAME strip of world by construction.
   Regenerate rather than hand-editing. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-2-1'] = {
  id: 'field-2-1', w: 10, h: 10, atlas: 'art/world.png',
  bg: 'art/bg/field-2-1.jpg',
  ground: [
    [17,20,17,20,16,17,18,17,16,16],
    [20,19,20,20,16,16,16,16,16,16],
    [19,20,17,20,16,16,16,16,17,16],
    [19,20,20,17,16,16,18,17,18,16],
    [17,19,19,16,17,18,16,16,16,16],
    [17,20,17,16,16,17,17,16,17,16],
    [20,19,20,17,16,16,16,16,18,16],
    [19,20,20,17,16,16,16,18,18,16],
    [20,20,20,16,16,16,18,16,16,17],
    [20,20,16,16,16,16,16,17,16,16]
  ],
  decor: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [26,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,26,0,0,0,0,0,0,0],
    [0,0,0,0,28,0,0,0,0,0],
    [0,0,0,0,0,0,0,26,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  block: [
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  markers: [
{ type:'fight', id:'pasture-2-1', name:'The Terraces', c:2, r:2, sprite:'sheep', dir:'SW', foes:['sheep', 'sheep', 'goat'] },
    /* THE CAUSEWAY back to the ruin the player woke in. */
    { type:'exit', c:1, r:5, to:'ruin-02', at:{ c:8, r:5 } },
    /* Vell the Outfitter — the novice set, just outside the ruin. */
    { type:'npc', id:'outfitter', name:'Vell the Outfitter', c:3, r:5 }
  ],
  neighbours: { n:'field-2-0', e:'field-3-1', s:'field-2-2', w:'field-1-1' }
};
