/* field-2-1 — beginner overworld screen (2,1) of a 5x3 grid.
   GENERATED by slicing one 46x28 global grid into 10x10 screens with a
   one-tile overlap (Dofus screen model: every map is the same size and is
   framed whole), so every edge shared with a neighbour is the SAME strip
   of world and is identical in ground/decor/block by construction.
   Pure data — regenerate rather than hand-edit seams. */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['field-2-1'] = {
  id: 'field-2-1', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [16,16,18,17,20,16,16,17,17,16],
    [17,16,16,17,20,17,16,18,16,17],
    [16,16,16,16,20,18,17,16,16,16],
    [16,16,16,16,20,16,16,18,18,16],
    [16,16,17,17,20,16,16,16,16,16],
    [16,16,16,17,20,17,16,16,16,17],
    [16,16,16,16,20,16,16,16,18,16],
    [16,16,16,17,20,16,16,16,16,16],
    [18,16,16,17,20,17,17,16,16,16],
    [16,16,17,16,20,16,16,16,17,18]
  ],
  decor: [
    [24,0,0,24,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,30,0,0,0,24,0,0,0],
    [0,0,24,0,0,0,24,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,30,0,0,0,0,0,0],
    [24,0,0,0,0,30,0,0,0,0],
    [0,0,0,24,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  block: [
    [1,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,0,0,0],
    [0,0,1,0,0,0,1,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
  ],
  markers: [
    { type:"fight", id:"woolly-2", name:"Wild Woolly", c:7, r:2, sprite:"sheep", dir:"SW", foes:["goat", "gecko", "gecko"] }
  ],
  neighbours: { n:"field-2-0", e:"field-3-1", s:"field-2-2", w:"field-1-1" }
};
