/* necro-3
   GENERATED by tools/mkdungeon.py — regenerate rather than hand-edit.
   The Necropolis, room 3 of 4 (alcoves). The Singing Vault */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['necro-3'] = {
  id: 'necro-3', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [3,1,5,3,2,3,1,2,3,1],
    [3,2,3,1,2,3,1,5,3,2],
    [1,2,3,1,5,3,2,3,1,2],
    [1,5,3,2,3,1,2,3,1,5],
    [2,3,1,2,3,1,5,3,2,3],
    [2,3,1,5,3,2,3,1,2,3],
    [5,3,2,3,1,2,3,1,5,3],
    [3,1,2,3,1,5,3,2,3,1],
    [3,1,5,3,2,3,1,2,3,1],
    [3,2,3,1,2,3,1,5,3,2]
  ],
  decor: [
    [8,8,8,8,9,8,8,8,8,8],
    [8,0,0,10,12,0,10,0,0,8],
    [8,0,0,10,0,0,10,0,0,8],
    [9,0,0,0,0,0,0,0,0,8],
    [8,0,0,0,0,0,0,0,0,8],
    [11,0,0,0,0,0,0,0,0,11],
    [8,0,0,0,0,0,0,0,0,9],
    [8,0,10,0,0,0,0,10,0,8],
    [8,0,10,0,0,12,0,10,0,8],
    [8,8,8,8,8,8,9,8,8,8]
  ],
  block: [
    [1,1,1,1,1,1,1,1,1,1],
    [1,0,0,1,1,0,1,0,0,1],
    [1,0,0,1,0,0,1,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,1,0,0,0,0,1,0,1],
    [1,0,1,0,0,1,0,1,0,1],
    [1,1,1,1,1,1,1,1,1,1]
  ],
  markers: [
    { type:'fight', id:'necro-fight-3', name:'The Singing Vault', c:5, r:3, sprite:'skelmage', dir:'SW', foes:['mage', 'mage', 'archer', 'grunt'] },
    { type:'exit', c:0, r:5, to:'necro-2', at:{ c:8, r:5 } },
    { type:'exit', c:9, r:5, to:'necro-4', at:{ c:1, r:5 } }
  ],
  /* joined by DOORS, not by edges — a dungeon has no seam to get wrong */
  neighbours: { n:null, e:null, s:null, w:null }
};
