/* necro-1
   GENERATED by tools/mkdungeon.py — regenerate rather than hand-edit.
   The Necropolis, room 1 of 4 (hall). The Long Aisle */
'use strict';
window.MAPS = window.MAPS || {};
window.MAPS['necro-1'] = {
  id: 'necro-1', w: 10, h: 10, atlas: 'art/world.png',
  ground: [
    [1,2,3,1,5,3,2,3,1,2],
    [1,5,3,2,3,1,2,3,1,5],
    [2,3,1,2,3,1,5,3,2,3],
    [2,3,1,5,3,2,3,1,2,3],
    [5,3,2,3,1,2,3,1,5,3],
    [3,1,2,3,1,5,3,2,3,1],
    [3,1,5,3,2,3,1,2,3,1],
    [3,2,3,1,2,3,1,5,3,2],
    [1,2,3,1,5,3,2,3,1,2],
    [1,5,3,2,3,1,2,3,1,5]
  ],
  decor: [
    [8,8,8,8,9,8,8,8,8,8],
    [8,0,0,0,0,0,0,0,0,8],
    [8,0,10,0,10,0,10,0,10,8],
    [9,0,0,0,0,0,0,0,0,8],
    [8,0,0,0,15,0,0,0,0,8],
    [11,0,0,0,0,0,0,0,0,11],
    [8,0,0,0,0,0,0,0,0,9],
    [8,0,10,0,10,0,10,0,10,8],
    [8,0,0,0,0,0,0,0,0,8],
    [8,8,8,8,8,8,9,8,8,8]
  ],
  block: [
    [1,1,1,1,1,1,1,1,1,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,1,0,1,0,1,0,1,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,0,0,1,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,1],
    [1,0,1,0,1,0,1,0,1,1],
    [1,0,0,0,0,0,0,0,0,1],
    [1,1,1,1,1,1,1,1,1,1]
  ],
  markers: [
    { type:'fight', id:'necro-fight-1', name:'The Long Aisle', c:5, r:3, sprite:'skelmage', dir:'SW', foes:['mage', 'archer', 'archer'] },
    { type:'exit', c:0, r:5, to:'field-4-2', at:{ c:5, r:6 } },
    { type:'exit', c:9, r:5, to:'necro-2', at:{ c:1, r:5 } }
  ],
  /* joined by DOORS, not by edges — a dungeon has no seam to get wrong */
  neighbours: { n:null, e:null, s:null, w:null }
};
